### ISSUE TITLE
Dropbox Wrapper = body not working well with multiple selection

### ISSUE THREAD

**Issue by gnbm** [sa-si-dev/virtual-select#144]
Hello.
I updated the library to version 1.0.29 (I was using 1.0.27) to take advantage of an issue that was reported to be fixed but got another issue. Basically, when we have dropboxWrapper='body' and we are using multiple selections, once we start selecting the options we can't any longer close the dropdown (we can even see the arrow switching):
![IssueBodyWrapperMultipleSelection](https://user-images.githubusercontent.com/29493222/167856610-7475aa06-e740-4b1f-a072-ed0573680bc1.gif)

Hope we can have this fixed asap. Thank you and continue the amazing work you're doing with this library.

**Comment by sa-si-dev** [comment]
Please share your page URL.

**Comment by JoaoFerreira-FrontEnd** [comment]
Hi team, 
I worked with @gnbm, and I'ld like to share the sample for this.
https://jsfiddle.net/joaoMFerreira/4g0s7unx/25/

I found out that the issue was replicated every time we destroy and initialize the same select, we are doing this because we need to update some parameters, and there isn't a method for that.

Apart from it I found out that the click listeners are not removed by the destroy() method. After I remove them by hand our issue was solved.

Not related with this repo, but I discover what I think is a typo on the popover, there is written "destory" where the events are removed.

Hope this helps to found the solution. 
Thank you for the waiting and support.

**Comment by sa-si-dev** [comment]
> Hi team, 
> I worked with @gnbm, and I'ld like to share the sample for this.
> https://jsfiddle.net/joaoMFerreira/4g0s7unx/25/
> 
> I found out that the issue was replicated every time we destroy and initialize the same select, we are doing this because we need to update some parameters, and there isn't a method for that.
> 
> Apart from it I found out that the click listeners are not removed by the destroy() method. After I remove them by hand our issue was solved.
> 
> Not related with this repo, but I discover what I think is a typo on the popover, there is written "destory" where the events are removed.
> 
> Hope this helps to found the solution. 
> Thank you for the waiting and support.

@JoaoFerreira-FrontEnd I think this could be the reason. I will check and fix it. Thanks for sharing it.

**Comment by sa-si-dev** [comment]
@gnbm This issue has been fixed in the [release v1.0.30](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.30)
