### ISSUE TITLE
[Feature Request] Combination of properties with allowNewOption.

### ISSUE THREAD

**Issue by gowravshekar** [sa-si-dev/virtual-select#32]
@sa-si-dev, Great work with the library. I have been testing the library with different combinations and made below observations.

1. `allowNewOption` and `selectedValue` doesn't work together.

If a new value is added with the above combination and upon editing the form with `selectedValue`, the select box shows empty.

2.   `allowNewOption` and `onServerSearch` combination.

With the above combination, is there a way to allow new option. Adding a new option manually with `searchValue` doesn't let the user know that it's a new option.

3. Value can be only of primitive type because of `valueKey` design.

`valueKey` should take a function which enable developers to pick an object as value. This will be useful especially with `allowNewOption` to distinguish between a new option selected by user(which will be primitive) and value selected by pre-defined option(which will be object).

**Comment by sa-si-dev** [comment]
@gowravshekar thank you for letting me know these issue.

I will check them and fix in the future release.

**Comment by gowrav-scienaptic** [comment]
Item1:

https://sa-si-dev.github.io/virtual-select/#/examples?id=preselect-value

If the selectedValue is not part of the default options set as we had `allowNewOption = true`, the new option should be automatically added and displayed in the input on editing the form. 

If default options are - Option 1, Option 2, Option 3 and selected value is Option 4 and `allowNewOption = true`, then input should show `Option 4`.

Item3:

What happens with a multi-select, when the new value is added and removed. It's very difficult to keep track of items selected by default options and added by users. One more use case is when the selected value needs to be an object instead of a scalar like in this [example](https://aurelia.io/docs/binding/selects#select-object).

**Comment by sa-si-dev** [comment]
@gowravshekar above issues have been fixed in the [release v1.0.9](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.9).

For item 3, you could use [getSelectedOptions()](https://sa-si-dev.github.io/virtual-select/#/methods?id=getselectedoptions) method.
